config/routes.rb
Rails.application.routes.draw do
  resources :communities
  resources :submissions
  devise_for :users
  get 'home/index'
  root to: "submissions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  has_many :submissions
end

app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :submission_image, SubmissionImageUploader
  # mount_uploader :submission_video, SubmissionVideoUploader
  belongs_to :user
  belongs_to :community

  validates :title, presence: true
  validates :body, length: { maximum: 8000 }
  validates :url, url: true, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :username
  validates_presence_of :username

  has_many :submissions
  has_many :communities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :find_communities

  protected

  def find_communities
    @communities = Community.all.order(:title)
  end

  def configure_permitted_parameters
    added_attrs = [:username] # this can grow to however many fields you need
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = current_user.communities.build
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = current_user.communities.build(community_params)
    @community.user_id = current_user.id

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.require(:community).permit(:name, :title, :description, :sidebar, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = current_user.submissions.build
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = current_user.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:title, :body, :url, :submission_image, :submission_video, :community_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, styles: "fill-current text-gray-400", title: nil)
    filename = "#{name}.svg"
    title ||= name.underscore.humanize
    inline_svg_tag(filename, aria: true, nocomment: true, title: title, class: styles)
  end

  def author_of(record)
    user_signed_in? && current_user.id == record.user_id
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/application/_basic_layout.html.erb
<div class="flex flex-wrap px-2 lg:px-8 mt-2 lg:mt-8 container m-auto">

  <div class="w-full md:w-2/3 pr-0 md:pr-6 mb-6">
    <div class="bg-white shadow rounded-sm">
      <%= yield :primary_content %>
    </div>
  </div>

  <div class="w-full md:w-1/3">
    <div class="bg-white shadow rounded-sm">
      <%= yield :secondary_content %>
    </div>
  </div>

</div>

app/views/communities/_community.html.erb
<div class="card flex flex-wrap items-center justify-between px-4 py-2">
  <div class="flex-1">
     <%= link_to community, class:"no-underline text-gray-700" do %>
      <p class="m-0 leading-tight">
        <span class="text-xs no-underline inline-flex items-center text-gray-600">
          <%= render_svg 'icons/conversation', styles: "w-3 fill-current text-gray-500 mr-1" %> w/<%= community.name %>
        </span>
      </p>
      <h3 class="m-0 leading-tight text-base"><%= community.title %><h3>
    <% end %>
  </div>
  <div class="text-xs font-normal">
    <%= link_to community, class: "no-underline" do %>
      <%= render_svg 'icons/view', styles: "w-4 fill-current text-gray-500", title: "View" %>
    <% end %>

    <% if author_of(community) %>
      <%= link_to edit_community_path(community), class: "no-underline ml-2" do %>
        <%= render_svg 'icons/edit', styles: "w-4 fill-current text-gray-500", title: "Edit" %>
      <% end %>

      <%= link_to community, class: "no-underline ml-2", method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= render_svg 'icons/delete', styles: "w-4 fill-current text-gray-500", title: "Delete" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/communities/_community_header.html.erb
<div class="bg-purple-600 text-white">
  <div class="container lg:p-10 p-4">
    <h1 class="lg:text-3xl text-lg">w/<%= community.name %></h1>
  </div>
</div>

app/views/communities/_form.html.erb
<%= form_with(model: community, local: true) do |form| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :sidebar %>
    <%= form.text_area :sidebar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/communities/_sidebar.html.erb
<div class="rounded">
  <div class="px-8 pt-6 pb-8">
    <div class="m-0 leading-tight flex items-center justify-between">
      <span class="text-xs no-underline inline-flex items-center text-gray-600">
        <%= render_svg 'icons/conversation', styles: "w-3 fill-current text-gray-500 mr-1" %> w/<%= community.name %>
      </span>
      <% if author_of(community) %>
        <%= link_to edit_community_path(community), class: "no-underline mr-2" do %>
          <%= render_svg 'icons/edit', styles: "w-4 fill-current text-gray-500", title: "Edit" %>
        <% end %>
      <% end %>
    </div>
    <h3 class="m-0 leading-tight text-lg"><%= community.title %></h3>

    <div class="flex flex-wrap justify-start items-center pt-2">
      <div class="w-1/2 border-r border-gray-400">
        <p class="m-0"><%= community.submissions.count %></p>
        <p class="m-0 text-xs">
          <%= pluralize(community.submissions.count, 'Submission') %>
        </p>
      </div>
      <div class="w-1/2 pl-4">
        <p class="m-0">< count ></p>
        <p class="m-0 text-xs">Subscribers</p>
      </div>
    </div>

    <hr class="border-b border-gray-400" />

    <div class="text-sm mb-6">
      <%= community.description %>
    </div>

    <hr class="border-b border-gray-400" />

    <div class="text-sm mb-6">
      <%= community.sidebar %>
    </div>
  </div>
</div>

app/views/communities/edit.html.erb
<% content_for :community_label, "Edit Community" %>

  <% content_for :primary_content do %>
    <div class="lg:p-10 pt-10 pb-10 px-4">
      <h1 class="text-xl font-normal mb-6">Editing Community</h1>
      <%= render 'form', community: @community %>
    </div>
  <% end %>

  <% content_for :secondary_content do %>
    <div class="px-8 pt-6 pb-8">
      <%= render_svg 'community', styles: 'max-w-full h-auto mb-4' %>
      <h4>Edit <%= @community.title %> community on webbit</h4>
      <p class="text-sm italic">Each community requires the following:</p>
      <ul class="mt-1 pl-4">
        <li>Name</li>
        <li>Title</li>
        <li>Description</li>
      </ul>
    </div>
  <% end %>

<%= render "basic_layout" %>

app/views/communities/index.html.erb
<% content_for :community_label, "All Communities" %>

<% content_for :primary_content do %>
  <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">Communities</h1>
    <%= render @communities %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <%= link_to 'New Community', new_community_path  if user_signed_in? %>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/new.html.erb
<% content_for :community_label, "Create community" %>

<% content_for :primary_content do %>
 <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">Create a Community</h1>
    <%= render 'form', community: @community %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-8 pt-6 pb-8">
    <%= render_svg 'community', styles: 'max-w-full h-auto mb-4' %>
    <h4>Create a new community on webbit</h4>
    <p class="text-sm italic">Each community requires the following:</p>
    <ul class="mt-1 pl-4">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>
  </div>
<% end %>

<%= render "basic_layout" %>

app/views/communities/show.html.erb
<% content_for :community_label, "w/#{@community.name}" %>

<%= render 'community_header', community: @community %>

<% content_for :primary_content do %>
  <% @community.submissions.each do |community| %>
    <%= render 'submissions/submission', submission: community %>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
  <%= render 'sidebar', community: @community %>
<% end %>

<%= render 'basic_layout' %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webbit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,400i,500,600,700' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-200 relative h-screen overflow-x-hidden">
    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div class="bg-red-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
        </div>
      <% end %>
      <% if type == "notice" %>
        <div class="bg-green-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
        </div>
      <% end %>
    <% end %>

    <nav class="js-nav bg-white py-2 border-b border-gray-400" role="navigation" arial-label="main navigation">

      <div class="flex flex-wrap items-center justify-center lg:justify-start lg:content-center px-4 lg:px-6">

        <%= link_to root_path, class:"leading-normal no-underline text-gray-800 my-2 md:my-0" do %>
          <h1 class="text-lg pr-2 font-bold">WEBBIT</h1>
        <% end %>

        <div class="flex flex-wrap justify-start w-full items-center lg:w-2/3">
          <div class="w-full lg:w-1/4 px-0 md:px-2 mb-2 lg:mb-0">

             <div class="dropdown rounded bg-white text-gray-700 ml-1 hover:bg-gray-200 z-50 relative">
              <%= link_to "#", class: "dropdown-target border no-underline flex justify-between text-gray-700 items-center pt-2 pb-2 pl-3 pr-1 text-sm rounded", role: "button" do %>
                  <%= content_for?(:community_label) ? yield(:community_label) : "Select a community" %>
                  <%= render_svg 'icons/chevron-down' %>
              <% end %>
              <ul class="dropdown-menu hidden shadow-lg leading-normal list-none p-0 rounded-b border-t text-sm z-50">

                  <% @communities.each do |community| %>
                    <li>
                      <%= link_to community, class: "bg-white px-4 py-2 hover:bg-purple-500 hover:text-white no-underline flex items-center"  do %>
                        <%= render_svg 'icons/conversation', styles:"avatar-sm mr-2 fill-current text-gray-500" %>
                        <span>w/</span> <%= community.name %>
                      <% end %>
                    </li>
                  <% end %>
              </ul>
            </div>

          </div>
          <div class="w-full lg:w-1/2 px-0 md:px-2">
            <div class="relative">
            <input class="input py-2 pl-10" id="search" type="text" placeholder="Search webbit">
            <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center px-3 text-gray-700">
              <svg class ="fill-current text-gray-500 h-4 w-4" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>search</title><path d="M22.414 19.586l-4.801-4.801A8.942 8.942 0 0 0 19 10a9 9 0 1 0-9 9 8.942 8.942 0 0 0 4.785-1.387l4.801 4.801c.39.391.902.586 1.414.586s1.024-.195 1.414-.586a2 2 0 0 0 0-2.828zM10 15c-2.757 0-5-2.243-5-5s2.243-5 5-5 5 2.243 5 5-2.243 5-5 5z" /></svg>
            </div>
            </div>
          </div>
        </div>

        <div class="w-full flex flex-wrap flex-1 items-center justify-end pt-4 lg:pt-0">
          <div class="mr-3">
            <% if !user_signed_in? %>
            <%= link_to "Login", new_user_session_path, class:"btn btn-outline btn-small mr-2" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-purple btn-small" %>
            <% end %>
            <% if user_signed_in? %>
               <%= link_to new_submission_path  do %>
                 <%= render_svg 'icons/create' %>
               <% end %>
            <% end %>
          </div>

          <% if user_signed_in? %>
            <div class="dropdown rounded bg-white text-gray-700 ml-1 hover:bg-gray-200">
                <%= link_to "#", class: "dropdown-target rounded border no-underline flex justify-between text-gray-700 uppercase tracking-wider text-xs font-semibold items-center pt-2 pb-2 pl-3 pr-1", role: "button" do %>
                  <%= current_user.username if current_user.username %>
                  <%= render_svg 'icons/chevron-down' %>
                <% end %>
                  <ul class="dropdown-menu hidden shadow-lg leading-normal list-none p-0 rounded-b border-t">
                    <h5 class="mt-2 uppercase text-xs text-gray-500 font-normal py-2 pl-3 tracking-wider">My Stuff</h5>



                    <li>
                      <%= link_to edit_user_registration_path, class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 flex items-center text-sm" do %>
                        <%= render_svg 'icons/settings', styles: "icon-md fill-current text-gray-600 mr-3" %> Account Settings
                      <% end %>
                    </li>

                    <li>
                      <%= link_to destroy_user_session_path, method: :delete, class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 rounded-b flex items-center text-sm"  do %>
                       <%= render_svg 'icons/signout', styles: "icon-md fill-current text-gray-600 mr-3" %> Sign out
                      <% end %>
                    </li>

                  </ul>
              </div>
            <% end %>
          </div>
        </div>
      </nav>
        <%= content_for?(:content) ? yield(:content) : yield %>
      <div class="js-notice dynamic-notice fadeInUp animated"></div>
  </body>
</html>

app/views/submissions/_actions.html.erb
<div class="pt-1 flex flex-wrap items-center">
  <%= link_to submission_path(submission, anchor: "comments"), class:"no-underline mr-2 flex items-center" do %>
      <%= render_svg 'icons/conversation', title: "Comments", styles: "fill-current text-gray-500 icon-sm hover:text-gray-700" %>
      <span class="text-sm text-gray-600 ml-2"><%#= pluralize(submission.comments.count, 'comment') %></span>
    <% end %>
  <% if author_of(submission)  %>
    <%= link_to edit_submission_path(submission), class:"no-underline mr-2" do %>
      <%= render_svg 'icons/edit', title: "Edit", styles: "fill-current text-gray-500 icon-sm hover:text-gray-700" %>
    <% end %>

    <%= link_to submission, method: :delete, class:"no-underline", data: { confirm: 'Are you sure?' } do %>
      <%= render_svg 'icons/delete', title: "Delete", styles: "fill-current text-gray-500 icon-sm hover:text-gray-700" %>
    <% end %>
  <% end %>
</div>

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation" class="border-red-400 p-4 rounded border bg-red-200 mb-6">
      <h2 class="text-sm heading text-red"><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul class="text-sm mt-2 text-red-500 pl-4">
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="mb-6 w-full lg:w-2/5">
    <div class="relative">
      <%= form.select(:community_id, Community.all.collect {|u| [u.name, u.id]}, { prompt: "Choose a community" }, { class: "select" } ) %>
      <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
        <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
      </div>
    </div>
  </div>

  
  <hr class="border border-gray-400 my-4"/>

  <div class="pb-10">
    <nav class="border-box">
      <ul id="nav-tab" class="tabs list-reset flex flex-wrap justify-between">

        <li class="active w-1/3 text-center cursor-pointer active" data-tab="text">
          <%= link_to "#text", class: "tab tab-first" do %>
            <%= render_svg 'icons/text' %> Text
          <% end %>
        </li>

        <li class="w-1/3 text-center cursor-pointer" data-tab="image_video">
          <%= link_to  "#image_video", class: "tab" do %>
             <%= render_svg 'icons/image' %> Image/Video
          <% end %>
        </li>

        <li class="w-1/3 text-center cursor-pointer" data-tab="url">
          <%= link_to "#link", class: "tab tab-last"  do %>
            <%= render_svg 'icons/link' %> Link
          <% end %>
        </li>
      </ul>
    </nav>
  </div>

  <div class="mb-6">
    <%= form.label :title, class:"label" %>
    <%= form.text_field :title, class:"input"  %>
  </div>

  <div class="mb-6 text">
    <%= form.label "Text", class: "label" %>
    <%= form.text_area :body, class: "input"  %>
  </div>

  <div class="mb-6 url">
    <%= form.label :url, class: "label" %>
    <%= form.text_field :url, class: "input" %>
  </div>

  <div class="image_video">
    <div class="mb-6">
      <%= form.label :submission_image, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg 'icons/image', styles: "fill-current text-gray-600 mr-2" %> Upload Image
        <%= form.file_field :submission_image, class: "hidden" %>
      </label>
    </div>

    <div class="mb-6">
      <%= form.label :submission_video, class: "label" %>
      <label class="btn btn-white btn-small inline-flex items-center">
        <%= render_svg 'icons/video', styles: "fill-current text-gray-600 mr-2 " %> Upload Video
        <%= form.file_field :submission_video, class: "hidden" %>
      </label>
    </div>
  </div>

  <div class="mb-6">
    <%= form.submit class: "btn btn-purple" %>
  </div>
<% end %>

app/views/submissions/_guidelines.html.erb
<h3 class="font-light mb-4">Posting to Webbit</h3>
<ol class="list-none leading-loose p-0 text-sm">
  <li class="border-b font-semibold py-1">Remember the human</li>
  <li class="border-b font-semibold py-1">Behave like you would in real life</li>
  <li class="border-b font-semibold py-1">Look for the original source of content</li>
  <li class="border-b font-semibold py-1">Search for duplicates before posting</li>
  <li class="border-b font-semibold py-1">Read the community’s rules</li>
</ol>

app/views/submissions/_posted_by.html.erb
<p class="text-gray-700 font-normal text-sm inline-block">Posted by <%= link_to "u/#{submission.user.username}", "#", class:"no-underline text-gray-700 font-normal hover:text-gray-700 hover:underline" %> <%= time_ago_in_words(submission.created_at) %> ago</p>

app/views/submissions/_submission.html.erb
<div class="border-b border-r border-l">
  <div class="p-4 flex items-start flex-wrap">

    <%= image_tag submission.submission_image.thumb.url, width: 80, height: 80 if submission.submission_image.present? %>

    <%= video_tag submission.submission_video if submission.submission_video.present? %>

    <div class="flex items-start">

      <div class="submission-voting text-xs pr-2">
        <%= render 'submissions/voting' %>
      </div>

      <div>
        <h3 class="mb-0 flex flex-wrap items-center text-base">
          <% submission_link = submission.url.present? ? submission.url : submission %>
          <%= link_to submission.title, submission_link, class: "no-underline" %>

          <% if submission.url %>
            <span class="pl-2 text-xs font-normal font-mono text-blue-400 tracking-tight">
              <%= link_to truncate(submission.url, length: 18), submission.url, class:"no-underline" %>
            </span>
          <% end %>
        </h3>

        <%= link_to community_path(submission.community), class:"no-underline text-gray-700 font-normal hover:text-gray-700 hover:underline text-sm inline-block" do %>
            w/<%= submission.community.name %>
        <% end %>

        <span class="mx-1 inline-block text-sm text-gray-700">•</span>

        <%= render 'submissions/posted_by', submission: submission %>
        <%= render 'submissions/actions', submission: submission %>
      </div>
    </div>
  </div>
</div>

app/views/submissions/_voting.html.erb
<%= link_to "#", class: "block text-center" do %>
  <%= render_svg "icons/up-vote", title: "upvote", styles: "fill-current text-gray-600 hover:text-gray-500" %>
<% end %>

<span class="text-gray-700 text-center block -mt-1">132</span>

<%= link_to "#", class: "block text-center" do %>
  <%= render_svg "icons/down-vote", title: "downvote", styles: "fill-current text-gray-600 hover:text-gray-500" %>
<% end %>

app/views/submissions/edit.html.erb
<% content_for :community_label, "Edit submission" %>
<%= content_for :primary_content do %>
  <div class="lg:p-10 pt-10 pb-10 px-4">
    <h1 class="text-xl font-normal mb-6">Editing submission <span class="italic"><%= @submission.title %></span></h1>

    <%= render 'form', submission: @submission %>
  </div>
<% end %>

<% content_for :secondary_content do %>
  <%= render "guidelines" %>
<% end %>

<%= render "basic_layout" %>

app/views/submissions/index.html.erb
<% content_for :community_label, "Select a community" %>

<% content_for :primary_content do %>
  <% if @submissions.exists? %>
    <%= render @submissions %>
  <% else %>
    <div class="p-10 text-center">
      <%= render_svg 'icons/empty' %>
      <p class="mb-4">Wow such empty... </p>
      <%= link_to 'Create a new post', new_submission_path, class: "btn btn-purple btn-small" %>
    </div>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
 <div class="px-8 pt-6 pb-8">
  <% unless user_signed_in? %>
    <%= image_tag "illustration.svg", class: "max-w-full" %>
    <h3>Explore</h3>
    <p class="text-gray-600 text-sm">Find your breaking news, sports, TV fan theories, or never-ending streams of cute animals.</p>
    <%= link_to "How Webbit works", "#", class: "btn btn-small btn-white my-2 block text-center" %>
  <% else %>
    <h3>Home</h3>
    <p class="text-gray-600 text-sm">Your personal Webbit frontpage. Come here to check in with your favorite communities.</p>
    <%= link_to 'Create Submission', new_submission_path, class: "btn btn-small btn-purple my-2 block text-center"  %>
    <%= link_to 'Create Community', new_community_path, class: "btn btn-small btn-white my-2 block text-center"  %>
  <% end %>
  </div>
<% end %>

<%= render "basic_layout" %>